version: '3'

services:
  paper-classification:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./merged_model_final:/app/merged_model_final
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge